direction: down

vars: {
  d2-config: {
    theme-id: 300
    layout-engine: elk
  }
}

browser: {
  label: "User"
  shape: person
}

client: {
  label: "Client"
  shape: rectangle
}

api: {
  label: "API"
  shape: rectangle
}

db: {
  label: "PostgreSQL"
  shape: cylinder
}

storage: {
  label: "Storage"
  shape: cylinder
}

oidc: {
  label: "SSO"
  shape: cloud
}

webhook: {
  label: "Webhook"
  shape: cloud
}

browser -> client
client -> api
oidc -> api
api -> db
api -> storage
api -> webhook
